name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite UTC
  workflow_dispatch:     # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run generator
        run: npm run generate

      - name: Commit and push output
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/
          git commit -m "update pacman graph" || echo "No changes"
          git push
